[package]
name = "actix-prometheus"
version = "0.1.0"
authors = ["orhanbalci <orhanbalci@gmail.com>"]

[dependencies]
actix-web = "1.0"
prometheus = "0.7.0"
lazy_static = "1.3.0"
futures = "0.1.28"

[dev-dependencies]
actix = "0.8.3"
