version: '2.1'

services:
    prometheus:
        image: prom/prometheus
        hostname: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        hostname: grafana
        ports:
            - "3000:3000"       
       
        
    